### ISSUE TITLE
Commented out Script?

### ISSUE THREAD

**Issue by ChrisCalderon** [SYWorks/waidps#1]
Is there any reason why you don't just put the script into a separate file? I am looking through the code and it seems like it can all be greatly simplified.It definitely doesn't need to be 16527 lines long.

**Comment by rf5g** [comment]
## why i get this error message after handshake capture?

Traceback (most recent call last):
  File "waidps.py", line 18755, in <module>
    Main()
  File "waidps.py", line 15301, in Main
    retkey=WaitingCommands(**builtin**.TIMEOUT,1)
  File "waidps.py", line 5657, in WaitingCommands
    RR=GetOptionCommands("1")
  File "waidps.py", line 5552, in GetOptionCommands
    OptAuditing("")
  File "waidps.py", line 1051, in OptAuditing
    AttackWPAProc(SELMAC,SELCHN,**builtin**.CUR_CLIENT,"")
  File "waidps.py", line 2437, in AttackWPAProc
    WPA_HANDSHAKE=CheckHandshake(**builtin**.CapFile,**builtin**.ATTACK_AP_BSSID,**builtin**.ATTACK_AP_ESSID)
  File "waidps.py", line 2852, in CheckHandshake
    shutil.copy2(capfile, **builtin**.HS_FileFull)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: ''

**Comment by sirpuffsalottabud** [comment]
I get the same error? HELP!!!

**Comment by FuryObsidian** [comment]
I get the same error to.. i run scrypt in linux kali last version. in folder /SYWorks/WAIDPS and /.SYWorks/WAIDPS/ and  up the folder level ( cd .. ) and not working. but error log different.

in folder /SYWorks/..  

`[.]   2020-01-05 01:57:34 - Checking for four-way handshake...                               
      1/4 (A>C) = 0		2/4 (C>A) = 0		 3/4 (A>C) = 0		4/4 (C>A) = 0
[i]   Handshake Found !!  Saving Handshake ....
      1/4 = 0		2/4 = 0		3/4 = 0		4/4 = 0
Traceback (most recent call last):
  File "./waidps.py", line 18755, in <module>
    Main()
  File "./waidps.py", line 15301, in Main
    retkey=WaitingCommands(__builtin__.TIMEOUT,1)
  File "./waidps.py", line 5657, in WaitingCommands
    RR=GetOptionCommands("1")
  File "./waidps.py", line 5552, in GetOptionCommands
    OptAuditing("")
  File "./waidps.py", line 856, in OptAuditing
    OptAuditing(Result);return
  File "./waidps.py", line 856, in OptAuditing
    OptAuditing(Result);return
  File "./waidps.py", line 856, in OptAuditing
    OptAuditing(Result);return
  File "./waidps.py", line 856, in OptAuditing
    OptAuditing(Result);return
  File "./waidps.py", line 720, in OptAuditing
    OptAuditing(HeaderLine);return
  File "./waidps.py", line 720, in OptAuditing
    OptAuditing(HeaderLine);return
  File "./waidps.py", line 856, in OptAuditing
    OptAuditing(Result);return
  File "./waidps.py", line 1051, in OptAuditing
    AttackWPAProc(SELMAC,SELCHN,__builtin__.CUR_CLIENT,"")
  File "./waidps.py", line 2437, in AttackWPAProc
    WPA_HANDSHAKE=CheckHandshake(__builtin__.CapFile,__builtin__.ATTACK_AP_BSSID,__builtin__.ATTACK_AP_ESSID)
  File "./waidps.py", line 2852, in CheckHandshake
    shutil.copy2(capfile, __builtin__.HS_FileFull)
  File "/usr/lib/python2.7/shutil.py", line 153, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: ''
`
other logs are almost the same.. Pleas HELP!!! Or project dead?
